"""Create tables owners, pets

Revision ID: 667fd37f09fb
Revises: 
Create Date: 2024-01-02 18:10:30.115136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667fd37f09fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
